# Project information
site_name: "Projeto Kokama"
site_description: "TODO"
site_author: "Grupo 03"
site_url: "https://fga-eps-mds.github.io/EPS-2020-2-G3/"

# Repository
repo_name: "Projeto Kokama"
repo_url: "https://github.com/fga-eps-mds/EPS-2020-2-G3/"

# Copyright
copyright: "Copyright &copy; 2021 Projeto Kokama"

# Theme settings
theme:
  logo: assets/img/logo.png
  favicon: assets/img/logo.png
  font:
    text: "Roboto"
    code: "Roboto Mono"
  features:
    - navigation.tabs
  language: "pt"
  name: "material"
  palette: 
    primary: "red"
    accent: "grey"

# Content Menu
nav:
  - Projeto:
      - Lean Inception:
        - Introdução: "project/lean-inception/introduction.md"
        - Visão do produto: "project/lean-inception/product-vision.md"
        - Produto é/faz: "project/lean-inception/is-is-not-does-does-not.md"
        - Objetivos do produto: "project/lean-inception/product-goals.md"
        - Personas: "project/lean-inception/personas.md"
        - Jornada do usuário: "project/lean-inception/user-journey.md"
        - Brainstorm: "project/lean-inception/brainstorm.md"
        - Revisão de funcionalidades: "project/lean-inception/functionalities-review.md"
        - Sequenciador: "project/lean-inception/sequencer.md"
        - Canvas MVP: "project/lean-inception/canvas-mvp.md"
      - Documento de visão: "project/vision-document.md"
      - Design:
        - Identidade visual: "project/visual-identity.md"
        - Protótipo de baixa fidelidade: "project/low-prototype.md"
        - Protótipo de média fidelidade: "project/mid-prototype.md"
        - Protótipo de alta fidelidade: "project/high-prototype.md"
      - Rich Picture: "project/rich-picture.md"
      - Comunidade:
        - Código de conduta: "project/CODE_OF_CONDUCT.md"
        - Diretrizes de contribuição: "project/CONTRIBUTING.md"
  - Gerência:
    - Plano de comunicação: "management/communication-plan.md"
    - Quadro de disponibilidade: "management/availability-board.md"
    - Roadmap de papeis: "management/role-roadmap.md"
    - Sprints:
      - Sprint 0:
        - Revisão e retrospectiva: "management/sprints/sprint-0.md"
      - Sprint 1:
        - Planejamento: "management/sprints/sprint-1-planning.md"
        - Revisão e retrospectiva: "management/sprints/sprint-1-review-retrospective.md"
    - Reuniões com PO: 
      - Reunião 1: "management/po-meetings/meeting-1.md" 

# Style
extra_css:
  - assets/css/extra.css

# Markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite:
      linenums: true
  - footnotes
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
